import React, { useState } from "react";
import JSZip from "jszip";
import { Download, FileText, Code, FolderArchive, ChevronDown, Cpu } from "lucide-react";
import { Button } from "@/components/ui/button";

interface ExportDropdownProps {
  plan: any;
  nodes: any[];
  dependencies: any[];
}

export default function ExportDropdown({ plan, nodes, dependencies }: ExportDropdownProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [exporting, setExporting] = useState(false);
  const [copiedPrompt, setCopiedPrompt] = useState(false);

  const toggleOpen = () => setIsOpen(!isOpen);

  // Generate Markdown report
  const handleExportMarkdown = () => {
    let md = `# Project Plan: ${plan.title}\n\n`;
    md += `## Product Brief\n${plan.brief || "No brief provided"}\n\n`;
    md += `## Architecture Overview\n${plan.settings?.briefSummary || "No summary"}\n\n`;
    md += `## Framework: ${plan.settings?.framework || "nextjs"}\n\n`;
    md += `---\n\n## Page Tree Nodes\n\n`;

    const pageNodes = nodes.filter((n) => n.type === "page");
    pageNodes.forEach((page) => {
      md += `### Page: ${page.name} (${page.metadata?.path || ""})\n`;
      md += `*Description:* ${page.description || "No description"}\n\n`;

      // Find children of this page
      const children = nodes.filter((n) => n.parent_id === page.id);
      if (children.length > 0) {
        md += `#### Decomposed Elements:\n`;
        children.forEach((child) => {
          md += `- **${child.name}** (${child.type.toUpperCase()})\n`;
          md += `  *Description:* ${child.description || "No description"}\n`;
          if (child.type === "component") {
            md += `  *Atomic Level:* ${child.metadata?.atomicType || "unknown"}\n`;
            if (child.metadata?.props && child.metadata.props.length > 0) {
              md += `  *Props:*\n`;
              child.metadata.props.forEach((p: any) => {
                md += `    - \`${p.name}: ${p.type}\` (${p.description})\n`;
              });
            }
          } else if (child.type === "hook") {
            md += `  *Inputs:* \`${child.metadata?.inputs || "None"}\`\n`;
            md += `  *Outputs:* \`${child.metadata?.outputs || "None"}\`\n`;
          } else if (child.type === "context") {
            md += `  *Value Shape:* \`${child.metadata?.valueShape || "None"}\`\n`;
          } else if (child.type === "data_shape") {
            md += `  *TypeScript Interface:*\n\`\`\`typescript\n${child.metadata?.tsInterface || ""}\n\`\`\`\n`;
          }
          
          // Dependencies
          const childDeps = dependencies.filter((d) => d.source_node_id === child.id);
          if (childDeps.length > 0) {
            md += `  *Dependencies:* `;
            const depNames = childDeps.map((d) => {
              const targetNode = nodes.find((n) => n.id === d.target_node_id);
              return targetNode ? `\`${targetNode.name}\` (${d.dependency_type})` : "";
            }).filter(Boolean);
            md += depNames.join(", ") + "\n";
          }
        });
        md += "\n";
      }
      md += "---\n\n";
    });

    // Download file
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `${plan.title.replace(/\s+/g, "_")}_Plan.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    setIsOpen(false);
  };

  // Export as JSON
  const handleExportJSON = () => {
    const data = {
      plan,
      nodes,
      dependencies
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `${plan.title.replace(/\s+/g, "_")}_Plan.json`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    setIsOpen(false);
  };

  // Export as ZIP boilerplate structure
  const handleExportZIP = async () => {
    try {
      setExporting(true);
      const zip = new JSZip();
      const framework = plan.settings?.framework || "nextjs";
      
      // 1. Add README.md
      let readme = `# Boilerplate for ${plan.title}\n\nGenerated by AI Frontend Project Planner.\n\n`;
      readme += `## Brief Summary\n${plan.settings?.briefSummary || "No summary"}\n\n`;
      
      if (framework === "vue") {
        readme += `## Folder Structure\nThis boilerplate follows atomic design principles inside a Vue / Nuxt application structure:\n`;
        readme += `- \`pages/\` - Nuxt routing page components\n`;
        readme += `- \`components/atoms/\` - Lowest level atomic components\n`;
        readme += `- \`components/molecules/\` - Combined atomic components\n`;
        readme += `- \`components/organisms/\` - Complex compound layout templates\n`;
        readme += `- \`composables/\` - Custom composable composition API scripts (Vue custom hooks equivalent)\n`;
        readme += `- \`stores/\` - Pinia state management files (Vue context equivalent)\n`;
        readme += `- \`types/\` - Shared TypeScript interfaces\n`;
        readme += `- \`mocks/\` - Mock data JSON structures\n`;
      } else if (framework === "svelte") {
        readme += `## Folder Structure\nThis boilerplate follows atomic design principles inside a SvelteKit project structure:\n`;
        readme += `- \`src/routes/\` - SvelteKit page routes (+page.svelte)\n`;
        readme += `- \`src/lib/components/atoms/\` - Lowest level atomic components\n`;
        readme += `- \`src/lib/components/molecules/\` - Combined atomic components\n`;
        readme += `- \`src/lib/components/organisms/\` - Complex layouts\n`;
        readme += `- \`src/lib/stores/\` - Svelte reactive stores (Svelte custom hooks & contexts equivalent)\n`;
        readme += `- \`src/lib/types/\` - TypeScript interfaces\n`;
        readme += `- \`src/lib/mocks/\` - Mock data modules\n`;
      } else {
        readme += `## Folder Structure\nThis boilerplate follows the atomic design principles inside a standard Next.js / React structure:\n`;
        readme += `- \`app/\` or \`src/pages/\` - Page routes and endpoints\n`;
        readme += `- \`components/atoms/\` - Lowest level UI components\n`;
        readme += `- \`components/molecules/\` - Combined atomic components\n`;
        readme += `- \`components/organisms/\` - Independent compound containers\n`;
        readme += `- \`hooks/\` - Custom React hooks\n`;
        readme += `- \`context/\` - React context state providers\n`;
        readme += `- \`types/\` - Shared TypeScript interfaces\n`;
        readme += `- \`mocks/\` - Mock data JSON structures\n`;
      }
      zip.file("README.md", readme);

      // 2. Iterate nodes and create files
      const pageNodes = nodes.filter((n) => n.type === "page");
      const subNodes = nodes.filter((n) => n.type !== "page");

      // Generate page files
      pageNodes.forEach((page) => {
        let cleanPath = page.metadata?.path || "";
        if (cleanPath.startsWith("/")) cleanPath = cleanPath.substring(1);
        if (cleanPath === "") cleanPath = "home";

        let pageContent = "";
        let pageFilePath = "";

        if (framework === "vue") {
          pageFilePath = `pages/${cleanPath}.vue`;
          pageContent = `<script setup lang="ts">
// Page: ${page.name}
// Route Path: ${page.metadata?.path || "/"}
// Description: ${page.description || ""}
</script>

<template>
  <div class="flex flex-col flex-1 p-8 bg-zinc-950 text-white min-h-screen">
    <header class="mb-8 border-b border-zinc-800 pb-4">
      <h1 class="text-3xl font-bold tracking-tight">${page.name}</h1>
      <p class="text-zinc-400 mt-1">${page.description}</p>
    </header>
    
    <main class="grid gap-6">
      <div class="border border-zinc-800 bg-zinc-900/50 rounded-xl p-6 text-zinc-500 border-dashed text-center">
        Place child Vue components here
      </div>
    </main>
  </div>
</template>
`;
        } else if (framework === "svelte") {
          pageFilePath = `src/routes/${cleanPath}/+page.svelte`;
          pageContent = `<script lang="ts">
  // Page: ${page.name}
  // Route Path: ${page.metadata?.path || "/"}
  // Description: ${page.description || ""}
</script>

<div class="flex flex-col flex-1 p-8 bg-zinc-950 text-white min-h-screen">
  <header class="mb-8 border-b border-zinc-800 pb-4">
    <h1 class="text-3xl font-bold tracking-tight">${page.name}</h1>
    <p class="text-zinc-400 mt-1">${page.description}</p>
  </header>
  
  <main class="grid gap-6">
    <div class="border border-zinc-800 bg-zinc-900/50 rounded-xl p-6 text-zinc-500 border-dashed text-center">
      Place child Svelte components here
    </div>
  </main>
</div>
`;
        } else {
          pageFilePath = `app/${cleanPath}/page.tsx`;
          pageContent = `// Page: ${page.name}
// Route Path: ${page.metadata?.path || "/"}
// Description: ${page.description || ""}

import React from 'react';

export default function ${page.name.replace(/\s+/g, "")}Page() {
  return (
    <div className="flex flex-col flex-1 p-8 bg-zinc-950 text-white min-h-screen">
      <header className="mb-8 border-b border-zinc-800 pb-4">
        <h1 className="text-3xl font-bold tracking-tight">${page.name}</h1>
        <p className="text-zinc-400 mt-1">${page.description}</p>
      </header>
      
      <main className="grid gap-6">
        <div className="border border-zinc-800 bg-zinc-900/50 rounded-xl p-6 text-zinc-500 border-dashed text-center">
          Place child components here
        </div>
      </main>
    </div>
  );
}
`;
        }
        zip.file(pageFilePath, pageContent);
      });

      // Generate child nodes
      subNodes.forEach((node) => {
        const nameClean = node.name.replace(/\s+/g, "");
        const depends = dependencies.filter((d) => d.source_node_id === node.id);
        const depImports = depends.map((d) => {
          const target = nodes.find((n) => n.id === d.target_node_id);
          if (!target) return "";
          const targetName = target.name.replace(/\s+/g, "");
          
          if (framework === "vue") {
            if (target.type === "component") {
              const atomicType = target.metadata?.atomicType || "atoms";
              const folder = atomicType === "atom" ? "atoms" : atomicType === "molecule" ? "molecules" : "organisms";
              return `import ${targetName} from '@/components/${folder}/${targetName}.vue';`;
            } else if (target.type === "hook") {
              return `import { ${targetName} } from '@/composables/${targetName}';`;
            } else if (target.type === "context") {
              return `import { use${targetName.replace(/Context$/, "")}Store } from '@/stores/${targetName}';`;
            } else if (target.type === "data_shape") {
              return `import type { ${targetName} } from '@/types/${targetName}';`;
            }
          } else if (framework === "svelte") {
            if (target.type === "component") {
              const atomicType = target.metadata?.atomicType || "atoms";
              const folder = atomicType === "atom" ? "atoms" : atomicType === "molecule" ? "molecules" : "organisms";
              return `import ${targetName} from '$lib/components/${folder}/${targetName}.svelte';`;
            } else if (target.type === "hook" || target.type === "context") {
              return `import { ${targetName} } from '$lib/stores/${targetName}';`;
            } else if (target.type === "data_shape") {
              return `import type { ${targetName} } from '$lib/types/${targetName}';`;
            }
          } else {
            if (target.type === "component") {
              const atomicType = target.metadata?.atomicType || "atoms";
              const folder = atomicType === "atom" ? "atoms" : atomicType === "molecule" ? "molecules" : "organisms";
              return `import { ${targetName} } from '@/components/${folder}/${targetName}';`;
            } else if (target.type === "hook") {
              return `import { ${targetName} } from '@/hooks/${targetName}';`;
            } else if (target.type === "context") {
              return `import { use${targetName.replace(/Context$/, "")} } from '@/context/${targetName}';`;
            } else if (target.type === "data_shape") {
              return `import type { ${targetName} } from '@/types/${targetName}';`;
            }
          }
          return "";
        }).filter(Boolean).join("\n");

        if (node.type === "component") {
          const atomicType = node.metadata?.atomicType || "atom";
          const folder = atomicType === "atom" ? "atoms" : atomicType === "molecule" ? "molecules" : "organisms";
          const props = node.metadata?.props || [];

          if (framework === "vue") {
            const propsDecl = props.length > 0
              ? `defineProps<{\n${props.map((p: any) => `  ${p.name}: ${p.type}; // ${p.description}`).join("\n")}\n}>();`
              : `// No props required`;

            const content = `<script setup lang="ts">
import { ref } from 'vue';
${depImports}

${propsDecl}
</script>

<template>
  <div class="p-4 border border-zinc-800 bg-zinc-900/40 backdrop-blur-md rounded-xl">
    <div class="text-sm font-semibold text-zinc-300">${node.name} (${atomicType})</div>
    <p class="text-xs text-zinc-500 mt-1">${node.description}</p>
    
    <!-- TODO: Implement layout -->
  </div>
</template>
`;
            zip.file(`components/${folder}/${nameClean}.vue`, content);
          } else if (framework === "svelte") {
            const propsDecl = props.length > 0
              ? `let { \n    ${props.map((p: any) => `${p.name}`).join(",\n    ")} \n  } = $props<{\n${props.map((p: any) => `    ${p.name}: ${p.type};`).join("\n")}\n  }>();`
              : `// No props required`;

            const content = `<script lang="ts">
  ${depImports}

  ${propsDecl}
</script>

<div class="p-4 border border-zinc-800 bg-zinc-900/40 backdrop-blur-md rounded-xl">
  <div class="text-sm font-semibold text-zinc-300">${node.name} (${atomicType})</div>
  <p class="text-xs text-zinc-500 mt-1">${node.description}</p>
  
  <!-- TODO: Implement layout -->
</div>
`;
            zip.file(`src/lib/components/${folder}/${nameClean}.svelte`, content);
          } else {
            const propsInterface = props.length > 0
              ? `export interface ${nameClean}Props {\n${props.map((p: any) => `  ${p.name}: ${p.type}; // ${p.description}`).join("\n")}\n}`
              : `export interface ${nameClean}Props {}`;

            const propsUsage = props.map((p: any) => p.name).join(", ");
            
            const content = `import React from 'react';
${depImports}

${propsInterface}

export function ${nameClean}({ ${propsUsage} }: ${nameClean}Props) {
  return (
    <div className="p-4 border border-zinc-800 bg-zinc-900/40 backdrop-blur-md rounded-xl">
      <div className="text-sm font-semibold text-zinc-300">${node.name} (${atomicType})</div>
      <p className="text-xs text-zinc-500 mt-1">${node.description}</p>
      
      {/* TODO: Add implementation layout */}
    </div>
  );
}
`;
            zip.file(`components/${folder}/${nameClean}.tsx`, content);
          }

        } else if (node.type === "hook") {
          if (framework === "vue") {
            const content = `import { ref, computed } from 'vue';
${depImports}

// Composable: ${node.name}
// Description: ${node.description}

export function ${nameClean}() {
  // TODO: Add Vue Composition state
  
  return {
    // Outputs matching: ${node.metadata?.outputs || "None"}
  };
}
`;
            zip.file(`composables/${nameClean}.ts`, content);
          } else if (framework === "svelte") {
            const content = `import { writable } from 'svelte/store';
${depImports}

// Composable store: ${node.name}
// Description: ${node.description}

export function ${nameClean}() {
  // TODO: Setup Svelte store or reactive helper
  
  return {
    // Outputs matching: ${node.metadata?.outputs || "None"}
  };
}
`;
            zip.file(`src/lib/stores/${nameClean}.ts`, content);
          } else {
            const content = `import { useState, useEffect } from 'react';
${depImports}

// Description: ${node.description}
// Inputs: ${node.metadata?.inputs || "None"}
// Outputs: ${node.metadata?.outputs || "None"}

export function ${nameClean}() {
  // TODO: Add custom state and hook logic
  
  return {
    // Return values matching: ${node.metadata?.outputs}
  };
}
`;
            zip.file(`hooks/${nameClean}.ts`, content);
          }

        } else if (node.type === "context") {
          if (framework === "vue") {
            const content = `import { defineStore } from 'pinia';
import { ref } from 'vue';
${depImports}

// Pinia Store: ${node.name}
// Description: ${node.description}
// Value Shape: ${node.metadata?.valueShape || "any"}

export const use${nameClean.replace(/Context$/, "").replace(/Store$/, "")}Store = defineStore('${nameClean.replace(/Context$/, "").replace(/Store$/, "").toLowerCase()}', () => {
  // TODO: Setup global reactive state and actions
  
  return {
    // State/Actions conforming to shape
  };
});
`;
            zip.file(`stores/${nameClean}.ts`, content);
          } else if (framework === "svelte") {
            const content = `import { writable } from 'svelte/store';
${depImports}

// Svelte Context Store: ${node.name}
// Description: ${node.description}
// Value Shape: ${node.metadata?.valueShape || "any"}

export const ${nameClean} = writable({
  // State conforming to value shape
});
`;
            zip.file(`src/lib/stores/${nameClean}.ts`, content);
          } else {
            const ctxClean = nameClean.replace(/Context$/, "");
            const content = `import React, { createContext, useContext, useState } from 'react';
${depImports}

// State shape defined: ${node.metadata?.valueShape || "any"}

export interface ${nameClean}Type {
  // Add properties matching value shape: ${node.metadata?.valueShape}
}

const ${nameClean} = createContext<${nameClean}Type | undefined>(undefined);

export function ${ctxClean}Provider({ children }: { children: React.ReactNode }) {
  // TODO: Setup context state management
  
  return (
    <${nameClean}.Provider value={{} as ${nameClean}Type}>
      {children}
    </${nameClean}.Provider>
  );
}

export function use${ctxClean}() {
  const context = useContext(${nameClean});
  if (!context) {
    throw new Error("use${ctxClean} must be used within a ${ctxClean}Provider");
  }
  return context;
}
`;
            zip.file(`context/${nameClean}.tsx`, content);
          }

        } else if (node.type === "data_shape") {
          const content = `// Data Shape: ${node.name}
// Description: ${node.description}

${node.metadata?.tsInterface || `export interface ${nameClean} {\n  id: string;\n}`}
`;
          const filePath = framework === "svelte" ? `src/lib/types/${nameClean}.ts` : `types/${nameClean}.ts`;
          zip.file(filePath, content);

        } else if (node.type === "mock_data") {
          const jsonVal = typeof node.metadata?.jsonData === "string" 
            ? node.metadata.jsonData 
            : JSON.stringify(node.metadata?.jsonData || [], null, 2);

          const content = `// Mock Data for: ${node.metadata?.dependsOn || "unknown"}
// Description: ${node.description}

export const ${nameClean} = ${jsonVal};
`;
          const filePath = framework === "svelte" ? `src/lib/mocks/${nameClean}.ts` : `mocks/${nameClean}.ts`;
          zip.file(filePath, content);
        }
      });

      // Write libraries to libraries.md
      const libNodes = nodes.filter((n) => n.type === "lib");
      if (libNodes.length > 0) {
        let libsMd = `# Third Party Libraries for ${plan.title}\n\n`;
        libNodes.forEach((lib) => {
          libsMd += `- **${lib.name}**: ${lib.description || "Required dependency"}\n`;
        });
        zip.file("Third-Party-Libraries.md", libsMd);
      }

      // Generate the ZIP
      const content = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(content);
      const link = document.createElement("a");
      link.href = url;
      link.setAttribute("download", `${plan.title.replace(/\s+/g, "_")}_Boilerplate.zip`);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      setIsOpen(false);
    } catch (err) {
      console.error("ZIP packaging failed:", err);
      alert("Failed to build ZIP file boilerplate.");
    } finally {
      setExporting(false);
    }
  };

  // Generate Master Prompt for Cursor/AI Agent
  const handleCopyMasterPrompt = () => {
    const framework = plan.settings?.framework || "nextjs";
    const fName = framework === "nextjs" 
      ? "Next.js (App Router)" 
      : framework === "react" 
      ? "React (SPA)" 
      : framework === "vue" 
      ? "Vue (Nuxt / Atomic)" 
      : "Svelte (SvelteKit / Atomic)";

    let prompt = `System Role: Act as an expert frontend engineer. Scaffold the complete application codebase in ${fName} using Tailwind CSS. Follow clean code, proper typing, atomic design component folders, and export fully functional files.\n\n`;
    
    prompt += `=========================================\n`;
    prompt += `PROJECT SPECIFICATION: ${plan.title}\n`;
    prompt += `=========================================\n\n`;
    prompt += `Brief Description:\n${plan.brief}\n\n`;
    prompt += `Architecture Summary:\n${plan.settings?.briefSummary || ""}\n\n`;
    
    prompt += `=========================================\n`;
    prompt += `FOLDER STRUCTURE TO USE:\n`;
    prompt += `=========================================\n`;
    if (framework === "vue") {
      prompt += `- pages/ (Nuxt page components matching route paths)\n`;
      prompt += `- components/atoms/ (basic UI primitives)\n`;
      prompt += `- components/molecules/ (composite atomic structures)\n`;
      prompt += `- components/organisms/ (complex modular templates)\n`;
      prompt += `- composables/ (composition API Vue composable files)\n`;
      prompt += `- stores/ (Pinia global stores)\n`;
      prompt += `- types/ (TypeScript interfaces)\n`;
      prompt += `- mocks/ (mock data structures)\n\n`;
    } else if (framework === "svelte") {
      prompt += `- src/routes/ (SvelteKit pages e.g. src/routes/dashboard/+page.svelte)\n`;
      prompt += `- src/lib/components/atoms/ (basic UI elements)\n`;
      prompt += `- src/lib/components/molecules/ (combined components)\n`;
      prompt += `- src/lib/components/organisms/ (independent complex blocks)\n`;
      prompt += `- src/lib/stores/ (Svelte writable stores / helpers)\n`;
      prompt += `- src/lib/types/ (TypeScript types)\n`;
      prompt += `- src/lib/mocks/ (mock data JSON/TS)\n\n`;
    } else {
      if (framework === "nextjs") {
        prompt += `- app/ (page route components matching path metadata)\n`;
      } else {
        prompt += `- src/pages/ (SPA pages)\n`;
      }
      prompt += `- components/atoms/ (basic reusable components)\n`;
      prompt += `- components/molecules/ (combinations of atoms)\n`;
      prompt += `- components/organisms/ (complex layouts)\n`;
      prompt += `- hooks/ (custom React hooks)\n`;
      prompt += `- context/ (state providers)\n`;
      prompt += `- types/ (TypeScript interfaces)\n`;
      prompt += `- mocks/ (JSON/TS mock data structures)\n\n`;
    }

    prompt += `=========================================\n`;
    prompt += `COMPONENTS, ROUTING, & DATA SECTIONS:\n`;
    prompt += `=========================================\n\n`;

    const pageNodes = nodes.filter((n) => n.type === "page");
    pageNodes.forEach((page) => {
      prompt += `### PAGE ROUTE: ${page.name}\n`;
      prompt += `- **Path**: \`${page.metadata?.path || "/"}\`\n`;
      prompt += `- **Description**: ${page.description || ""}\n`;
      
      const children = nodes.filter((n) => n.parent_id === page.id);
      if (children.length > 0) {
        prompt += `- **Decomposed Sub-Elements**:\n`;
        children.forEach((child) => {
          const typeLabel = child.type === "context" && framework === "vue" 
            ? "PINIA STORE" 
            : child.type === "context" && framework === "svelte"
            ? "SVELTE STORE"
            : child.type === "hook" && framework === "vue"
            ? "COMPOSABLE"
            : child.type.toUpperCase();

          prompt += `  * **${child.name}** (${typeLabel})\n`;
          prompt += `    - *Description*: ${child.description || ""}\n`;
          if (child.type === "component") {
            prompt += `    - *Atomic Level*: ${child.metadata?.atomicType || "component"}\n`;
            if (child.metadata?.props && child.metadata.props.length > 0) {
              prompt += `    - *Props*:\n`;
              child.metadata.props.forEach((p: any) => {
                prompt += `      - \`${p.name}: ${p.type}\` (${p.description})\n`;
              });
            }
          } else if (child.type === "hook") {
            prompt += `    - *Inputs/Parameters*: ${child.metadata?.inputs || "None"}\n`;
            prompt += `    - *Outputs/Returns*: ${child.metadata?.outputs || "None"}\n`;
          } else if (child.type === "context") {
            prompt += `    - *Value Shape*: ${child.metadata?.valueShape || ""}\n`;
          } else if (child.type === "data_shape") {
            prompt += `    - *TS Interface*:\n\`\`\`typescript\n${child.metadata?.tsInterface || ""}\n\`\`\`\n`;
          } else if (child.type === "mock_data") {
            prompt += `    - *Conforms to*: ${child.metadata?.dependsOn || ""}\n`;
            prompt += `    - *Mock Data Sample*:\n${typeof child.metadata?.jsonData === "string" ? child.metadata.jsonData : JSON.stringify(child.metadata?.jsonData || [], null, 2)}\n`;
          }
          
          // Dependencies
          const childDeps = dependencies.filter((d) => d.source_node_id === child.id);
          if (childDeps.length > 0) {
            const depList = childDeps.map((d) => {
              const targetNode = nodes.find((n) => n.id === d.target_node_id);
              return targetNode ? `\`${targetNode.name}\` (${d.dependency_type})` : "";
            }).filter(Boolean);
            prompt += `    - *Dependencies*: ${depList.join(", ")}\n`;
          }
        });
      }
      prompt += `\n-----------------------------------------\n\n`;
    });

    const libNodes = nodes.filter((n) => n.type === "lib");
    if (libNodes.length > 0) {
      prompt += `=========================================\n`;
      prompt += `REQUIRED THIRD-PARTY LIBRARIES:\n`;
      prompt += `=========================================\n`;
      libNodes.forEach((lib) => {
        prompt += `- **${lib.name}**: ${lib.description || ""}\n`;
      });
      prompt += `\n`;
    }

    prompt += `=========================================\n`;
    prompt += `STEP-BY-STEP IMPLEMENTATION INSTRUCTIONS FOR AI AGENT:\n`;
    prompt += `=========================================\n`;
    if (framework === "vue") {
      prompt += `1. Create all Types/Interfaces first in types/ directory.\n`;
      prompt += `2. Create Mock Data modules in mocks/ folder.\n`;
      prompt += `3. Set up Pinia stores in stores/ and custom composables in composables/.\n`;
      prompt += `4. Scaffold Atoms (lowest-level components) using composition API.\n`;
      prompt += `5. Combine Atoms to create Molecules.\n`;
      prompt += `6. Assemble Molecules and Composables to build Organisms.\n`;
      prompt += `7. Finally, integrate the Organisms inside Nuxt pages under pages/ directory.\n`;
      prompt += `8. Style using Tailwind CSS classes with modern HSL tailwind conventions.\n`;
      prompt += `9. Ensure all imports are correctly relative or match project alias conventions (e.g. '@/*').\n\n`;
    } else if (framework === "svelte") {
      prompt += `1. Create all Types/Interfaces first in src/lib/types/ directory.\n`;
      prompt += `2. Create Mock Data modules in src/lib/mocks/ folder.\n`;
      prompt += `3. Set up Svelte stores/helpers in src/lib/stores/.\n`;
      prompt += `4. Scaffold Atoms (lowest-level components) using Svelte 5 runes ($props, $state).\n`;
      prompt += `5. Combine Atoms to create Molecules.\n`;
      prompt += `6. Assemble Molecules to build Organisms.\n`;
      prompt += `7. Finally, integrate the Organisms inside SvelteKit routes (+page.svelte).\n`;
      prompt += `8. Style using Tailwind CSS classes with modern HSL tailwind conventions.\n`;
      prompt += `9. Ensure all imports are correctly relative or match project alias conventions (e.g. '$lib/*').\n\n`;
    } else {
      prompt += `1. Create all Types/Interfaces first in types/ directory.\n`;
      prompt += `2. Create Mock Data modules in mocks/ folder for styling/testing.\n`;
      prompt += `3. Set up Context State Providers in context/ and custom React hooks in hooks/.\n`;
      prompt += `4. Scaffold Atoms (lowest-level components) using mock data and mock contexts if needed.\n`;
      prompt += `5. Combine Atoms to create Molecules.\n`;
      prompt += `6. Assemble Molecules and Hooks to build Organisms.\n`;
      prompt += `7. Finally, integrate the Organisms inside page routing files to form the final routes.\n`;
      prompt += `8. Style using Tailwind CSS classes with modern HSL tailwind conventions.\n`;
      prompt += `9. Ensure all imports are correctly relative or match project alias conventions (e.g. '@/*').\n\n`;
    }
    prompt += `Please generate the complete codebase step-by-step now.`;

    navigator.clipboard.writeText(prompt);
    setCopiedPrompt(true);
    setTimeout(() => {
      setCopiedPrompt(false);
      setIsOpen(false);
    }, 1500);
  };

  return (
    <div className="relative">
      <Button
        onClick={toggleOpen}
        variant="outline"
        className="flex items-center gap-1.5 border-border bg-card/60 hover:bg-muted text-foreground hover:text-foreground rounded-lg h-9 px-3 text-xs cursor-pointer font-medium transition-colors"
      >
        <Download className="h-3.5 w-3.5" />
        Export Plan
        <ChevronDown className="h-3 w-3 opacity-60" />
      </Button>

      {isOpen && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setIsOpen(false)} />
          <div className="absolute right-0 mt-2 w-56 rounded-xl border border-border bg-card shadow-2xl p-1.5 z-50 animate-in fade-in slide-in-from-top-2 duration-150">
            <button
              onClick={handleCopyMasterPrompt}
              className="w-full flex items-center gap-2.5 px-3 py-2 text-xs text-muted-foreground hover:text-foreground hover:bg-muted/50 rounded-lg text-left transition-colors cursor-pointer"
            >
              <Cpu className="h-4 w-4 text-amber-500" />
              {copiedPrompt ? "Master Prompt Copied!" : "Copy AI Master Prompt"}
            </button>
            
            <div className="h-px bg-border my-1" />

            <button
              onClick={handleExportMarkdown}
              className="w-full flex items-center gap-2.5 px-3 py-2 text-xs text-muted-foreground hover:text-foreground hover:bg-muted/50 rounded-lg text-left transition-colors cursor-pointer"
            >
              <FileText className="h-4 w-4 text-blue-500" />
              Download Markdown Report
            </button>
            <button
              onClick={handleExportJSON}
              className="w-full flex items-center gap-2.5 px-3 py-2 text-xs text-muted-foreground hover:text-foreground hover:bg-muted/50 rounded-lg text-left transition-colors cursor-pointer"
            >
              <Code className="h-4 w-4 text-purple-500" />
              Download JSON Schema
            </button>
            <button
              onClick={handleExportZIP}
              disabled={exporting}
              className="w-full flex items-center gap-2.5 px-3 py-2 text-xs text-muted-foreground hover:text-foreground hover:bg-muted/50 rounded-lg text-left transition-colors cursor-pointer disabled:opacity-50"
            >
              {exporting ? (
                <div className="h-4 w-4 border-2 border-zinc-400 border-t-transparent rounded-full animate-spin" />
              ) : (
                <FolderArchive className="h-4 w-4 text-emerald-500" />
              )}
              Download Boilerplate ZIP
            </button>
          </div>
        </>
      )}
    </div>
  );
}
