import React, { useState } from "react";
import JSZip from "jszip";
import { Download, FileText, Code, FolderArchive, ChevronDown } from "lucide-react";
import { Button } from "@/components/ui/button";

interface ExportDropdownProps {
  plan: any;
  nodes: any[];
  dependencies: any[];
}

export default function ExportDropdown({ plan, nodes, dependencies }: ExportDropdownProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [exporting, setExporting] = useState(false);

  const toggleOpen = () => setIsOpen(!isOpen);

  // Generate Markdown report
  const handleExportMarkdown = () => {
    let md = `# Project Plan: ${plan.title}\n\n`;
    md += `## Product Brief\n${plan.brief || "No brief provided"}\n\n`;
    md += `## Architecture Overview\n${plan.settings?.briefSummary || "No summary"}\n\n`;
    md += `## Framework: ${plan.settings?.framework || "nextjs"}\n\n`;
    md += `---\n\n## Page Tree Nodes\n\n`;

    const pageNodes = nodes.filter((n) => n.type === "page");
    pageNodes.forEach((page) => {
      md += `### Page: ${page.name} (${page.metadata?.path || ""})\n`;
      md += `*Description:* ${page.description || "No description"}\n\n`;

      // Find children of this page
      const children = nodes.filter((n) => n.parent_id === page.id);
      if (children.length > 0) {
        md += `#### Decomposed Elements:\n`;
        children.forEach((child) => {
          md += `- **${child.name}** (${child.type.toUpperCase()})\n`;
          md += `  *Description:* ${child.description || "No description"}\n`;
          if (child.type === "component") {
            md += `  *Atomic Level:* ${child.metadata?.atomicType || "unknown"}\n`;
            if (child.metadata?.props && child.metadata.props.length > 0) {
              md += `  *Props:*\n`;
              child.metadata.props.forEach((p: any) => {
                md += `    - \`${p.name}: ${p.type}\` (${p.description})\n`;
              });
            }
          } else if (child.type === "hook") {
            md += `  *Inputs:* \`${child.metadata?.inputs || "None"}\`\n`;
            md += `  *Outputs:* \`${child.metadata?.outputs || "None"}\`\n`;
          } else if (child.type === "context") {
            md += `  *Value Shape:* \`${child.metadata?.valueShape || "None"}\`\n`;
          } else if (child.type === "data_shape") {
            md += `  *TypeScript Interface:*\n\`\`\`typescript\n${child.metadata?.tsInterface || ""}\n\`\`\`\n`;
          }
          
          // Dependencies
          const childDeps = dependencies.filter((d) => d.source_node_id === child.id);
          if (childDeps.length > 0) {
            md += `  *Dependencies:* `;
            const depNames = childDeps.map((d) => {
              const targetNode = nodes.find((n) => n.id === d.target_node_id);
              return targetNode ? `\`${targetNode.name}\` (${d.dependency_type})` : "";
            }).filter(Boolean);
            md += depNames.join(", ") + "\n";
          }
        });
        md += "\n";
      }
      md += "---\n\n";
    });

    // Download file
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `${plan.title.replace(/\s+/g, "_")}_Plan.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    setIsOpen(false);
  };

  // Export as JSON
  const handleExportJSON = () => {
    const data = {
      plan,
      nodes,
      dependencies
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `${plan.title.replace(/\s+/g, "_")}_Plan.json`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    setIsOpen(false);
  };

  // Export as ZIP boilerplate structure
  const handleExportZIP = async () => {
    try {
      setExporting(true);
      const zip = new JSZip();
      
      // 1. Add README.md
      let readme = `# Boilerplate for ${plan.title}\n\nGenerated by Frontend Project Planner.\n\n`;
      readme += `## Brief Summary\n${plan.settings?.briefSummary || "No summary"}\n\n`;
      readme += `## Folder Structure\nThis boilerplate follows the atomic design principles inside a standard Next.js App Router structure:\n`;
      readme += `- \`app/\` - Page routes and endpoints\n`;
      readme += `- \`components/atoms/\` - Lowest level UI components\n`;
      readme += `- \`components/molecules/\` - Combined atomic components\n`;
      readme += `- \`components/organisms/\` - Independent compound containers\n`;
      readme += `- \`hooks/\` - Custom React hooks\n`;
      readme += `- \`context/\` - React context state providers\n`;
      readme += `- \`types/\` - Shared TypeScript interfaces\n`;
      readme += `- \`mocks/\` - Mock data JSON structures\n`;
      zip.file("README.md", readme);

      // 2. Iterate nodes and create files
      const pageNodes = nodes.filter((n) => n.type === "page");
      const subNodes = nodes.filter((n) => n.type !== "page");

      // Generate page files
      pageNodes.forEach((page) => {
        // Clean up path, remove leading slash
        let cleanPath = page.metadata?.path || "";
        if (cleanPath.startsWith("/")) cleanPath = cleanPath.substring(1);
        if (cleanPath === "") cleanPath = "home";

        const fileContent = `// Page: ${page.name}
// Route Path: ${page.metadata?.path || "/"}
// Description: ${page.description || ""}

import React from 'react';

export default function ${page.name.replace(/\s+/g, "")}Page() {
  return (
    <div className="flex flex-col flex-1 p-8 bg-zinc-950 text-white min-h-screen">
      <header className="mb-8 border-b border-zinc-800 pb-4">
        <h1 className="text-3xl font-bold tracking-tight">${page.name}</h1>
        <p className="text-zinc-400 mt-1">${page.description}</p>
      </header>
      
      <main className="grid gap-6">
        <div className="border border-zinc-800 bg-zinc-900/50 rounded-xl p-6 text-zinc-500 border-dashed text-center">
          Place child components here
        </div>
      </main>
    </div>
  );
}
`;
        zip.file(`app/${cleanPath}/page.tsx`, fileContent);
      });

      // Generate child nodes
      subNodes.forEach((node) => {
        const nameClean = node.name.replace(/\s+/g, "");
        const depends = dependencies.filter((d) => d.source_node_id === node.id);
        const depImports = depends.map((d) => {
          const target = nodes.find((n) => n.id === d.target_node_id);
          if (!target) return "";
          const targetName = target.name.replace(/\s+/g, "");
          if (target.type === "component") {
            const atomicType = target.metadata?.atomicType || "atoms";
            return `import { ${targetName} } from '@/components/${atomicType === "atom" ? "atoms" : atomicType === "molecule" ? "molecules" : "organisms"}/${targetName}';`;
          } else if (target.type === "hook") {
            return `import { ${targetName} } from '@/hooks/${targetName}';`;
          } else if (target.type === "context") {
            return `import { use${targetName.replace(/Context$/, "")} } from '@/context/${targetName}';`;
          } else if (target.type === "data_shape") {
            return `import { ${targetName} } from '@/types/${targetName}';`;
          }
          return "";
        }).filter(Boolean).join("\n");

        if (node.type === "component") {
          const atomicType = node.metadata?.atomicType || "atom";
          const folder = atomicType === "atom" ? "atoms" : atomicType === "molecule" ? "molecules" : "organisms";
          
          const props = node.metadata?.props || [];
          const propsInterface = props.length > 0
            ? `export interface ${nameClean}Props {\n${props.map((p: any) => `  ${p.name}: ${p.type}; // ${p.description}`).join("\n")}\n}`
            : `export interface ${nameClean}Props {}`;

          const propsUsage = props.map((p: any) => p.name).join(", ");
          
          const content = `import React from 'react';
${depImports}

${propsInterface}

export function ${nameClean}({ ${propsUsage} }: ${nameClean}Props) {
  return (
    <div className="p-4 border border-zinc-800 bg-zinc-900/40 backdrop-blur-md rounded-xl">
      <div className="text-sm font-semibold text-zinc-300">${node.name} (${atomicType})</div>
      <p className="text-xs text-zinc-500 mt-1">${node.description}</p>
      
      {/* TODO: Add implementation layout */}
    </div>
  );
}
`;
          zip.file(`components/${folder}/${nameClean}.tsx`, content);

        } else if (node.type === "hook") {
          const content = `import { useState, useEffect } from 'react';
${depImports}

// Description: ${node.description}
// Inputs: ${node.metadata?.inputs || "None"}
// Outputs: ${node.metadata?.outputs || "None"}

export function ${nameClean}() {
  // TODO: Add custom state and hook logic
  
  return {
    // Return values matching: ${node.metadata?.outputs}
  };
}
`;
          zip.file(`hooks/${nameClean}.ts`, content);

        } else if (node.type === "context") {
          const ctxClean = nameClean.replace(/Context$/, "");
          const content = `import React, { createContext, useContext, useState } from 'react';
${depImports}

// State shape defined: ${node.metadata?.valueShape || "any"}

export interface ${nameClean}Type {
  // Add properties matching value shape: ${node.metadata?.valueShape}
}

const ${nameClean} = createContext<${nameClean}Type | undefined>(undefined);

export function ${ctxClean}Provider({ children }: { children: React.ReactNode }) {
  // TODO: Setup context state management
  
  return (
    <${nameClean}.Provider value={{} as ${nameClean}Type}>
      {children}
    </${nameClean}.Provider>
  );
}

export function use${ctxClean}() {
  const context = useContext(${nameClean});
  if (!context) {
    throw new Error("use${ctxClean} must be used within a ${ctxClean}Provider");
  }
  return context;
}
`;
          zip.file(`context/${nameClean}.tsx`, content);

        } else if (node.type === "data_shape") {
          const content = `// Data Shape: ${node.name}
// Description: ${node.description}

${node.metadata?.tsInterface || `export interface ${nameClean} {\n  id: string;\n}`}
`;
          zip.file(`types/${nameClean}.ts`, content);

        } else if (node.type === "mock_data") {
          const jsonVal = typeof node.metadata?.jsonData === "string" 
            ? node.metadata.jsonData 
            : JSON.stringify(node.metadata?.jsonData || [], null, 2);

          const content = `// Mock Data for: ${node.metadata?.dependsOn || "unknown"}
// Description: ${node.description}

export const ${nameClean} = ${jsonVal};
`;
          zip.file(`mocks/${nameClean}.ts`, content);
        }
      });

      // Write libraries to libraries.md
      const libNodes = nodes.filter((n) => n.type === "lib");
      if (libNodes.length > 0) {
        let libsMd = `# Third Party Libraries for ${plan.title}\n\n`;
        libNodes.forEach((lib) => {
          libsMd += `- **${lib.name}**: ${lib.description || "Required dependency"}\n`;
        });
        zip.file("Third-Party-Libraries.md", libsMd);
      }

      // Generate the ZIP
      const content = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(content);
      const link = document.createElement("a");
      link.href = url;
      link.setAttribute("download", `${plan.title.replace(/\s+/g, "_")}_Boilerplate.zip`);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      setIsOpen(false);
    } catch (err) {
      console.error("ZIP packaging failed:", err);
      alert("Failed to build ZIP file boilerplate.");
    } finally {
      setExporting(false);
    }
  };

  return (
    <div className="relative">
      <Button
        onClick={toggleOpen}
        variant="outline"
        className="flex items-center gap-1.5 border-border bg-card/60 hover:bg-muted text-foreground hover:text-foreground rounded-lg h-9 px-3 text-xs cursor-pointer font-medium transition-colors"
      >
        <Download className="h-3.5 w-3.5" />
        Export Plan
        <ChevronDown className="h-3 w-3 opacity-60" />
      </Button>

      {isOpen && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setIsOpen(false)} />
          <div className="absolute right-0 mt-2 w-56 rounded-xl border border-border bg-card shadow-2xl p-1.5 z-50 animate-in fade-in slide-in-from-top-2 duration-150">
            <button
              onClick={handleExportMarkdown}
              className="w-full flex items-center gap-2.5 px-3 py-2 text-xs text-muted-foreground hover:text-foreground hover:bg-muted/50 rounded-lg text-left transition-colors cursor-pointer"
            >
              <FileText className="h-4 w-4 text-blue-500" />
              Download Markdown Report
            </button>
            <button
              onClick={handleExportJSON}
              className="w-full flex items-center gap-2.5 px-3 py-2 text-xs text-muted-foreground hover:text-foreground hover:bg-muted/50 rounded-lg text-left transition-colors cursor-pointer"
            >
              <Code className="h-4 w-4 text-purple-500" />
              Download JSON Schema
            </button>
            <button
              onClick={handleExportZIP}
              disabled={exporting}
              className="w-full flex items-center gap-2.5 px-3 py-2 text-xs text-muted-foreground hover:text-foreground hover:bg-muted/50 rounded-lg text-left transition-colors cursor-pointer disabled:opacity-50"
            >
              {exporting ? (
                <div className="h-4 w-4 border-2 border-zinc-400 border-t-transparent rounded-full animate-spin" />
              ) : (
                <FolderArchive className="h-4 w-4 text-emerald-500" />
              )}
              Download Boilerplate ZIP
            </button>
          </div>
        </>
      )}
    </div>
  );
}
